	spring.application.name=medical-ai-transcriber
spring.main.allow-bean-definition-overriding=true
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/medic_ai
spring.datasource.username=admin
spring.datasource.password=medic_ai@10
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# OpenAI API Key
openai.api-key=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

# LangChain4j Chat Model Configuration
langchain4j.open-ai.chat-model.api-key=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
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.0

# LangChain4j Audio Transcription Model Configuration
langchain4j.open-ai.audio-transcription-model.api-key=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
langchain4j.open-ai.audio-transcription-model.model-name=whisper-1

#r2
r2.account.id=3c90b968856872aa377916d962bfb6a8
r2.bucket.name=medic-ai-audios
r2.access.key.id=d7e619e23be19c9e42cac92b0c2d191d
r2.secret.access.key=5c9e460d34a30c8c401316e8a3ef93984823350da813f3a2306fbadc033b1b59

#security
api.security.token.secret=meu-segredo-super-secreto